"""mediafile

Revision ID: 0ef968fa9623
Revises: d98bf7135565
Create Date: 2026-04-23 12:40:31.620805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef968fa9623'
down_revision: Union[str, None] = 'd98bf7135565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediafile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mediafile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mediafile_filename'), ['filename'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediafile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mediafile_filename'))

    op.drop_table('mediafile')
    # ### end Alembic commands ###
