"""move_rotation_transition_to_zone

Revision ID: 0f69551c6f1f
Revises: ea61d47a595a
Create Date: 2026-04-23 15:37:22.466933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f69551c6f1f'
down_revision: Union[str, None] = 'ea61d47a595a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layoutzone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_seconds', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('transition', sa.String(), nullable=False, server_default='fade'))
        batch_op.add_column(sa.Column('transition_direction', sa.String(), nullable=False, server_default='left'))

    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('rotation_seconds')
        batch_op.drop_column('transition_direction')
        batch_op.drop_column('transition')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition', sa.VARCHAR(), server_default=sa.text("'fade'"), nullable=False))
        batch_op.add_column(sa.Column('transition_direction', sa.VARCHAR(), server_default=sa.text("'left'"), nullable=False))
        batch_op.add_column(sa.Column('rotation_seconds', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('layoutzone', schema=None) as batch_op:
        batch_op.drop_column('transition_direction')
        batch_op.drop_column('transition')
        batch_op.drop_column('rotation_seconds')

    # ### end Alembic commands ###
