"""remove_screen_aspect_ratio

Revision ID: 1ca11bebfd6b
Revises: 0f69551c6f1f
Create Date: 2026-04-23 15:45:38.138276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca11bebfd6b'
down_revision: Union[str, None] = '0f69551c6f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('aspect_ratio')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aspect_ratio', sa.VARCHAR(), server_default=sa.text("'16:9'"), nullable=False))

    # ### end Alembic commands ###
