"""screen-transition

Revision ID: 230d563f1adf
Revises: 5a2902fd6fa7
Create Date: 2026-04-23 11:47:15.787372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230d563f1adf'
down_revision: Union[str, None] = '5a2902fd6fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition', sa.String(), nullable=False, server_default='fade'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('transition')

    # ### end Alembic commands ###
