"""init

Revision ID: 236b31ab6b7f
Revises: 
Create Date: 2026-04-24 09:26:12.033101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '236b31ab6b7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aspect_ratio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aspect_ratio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediafolder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['mediafolder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('edit_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_edit_token'), ['edit_token'], unique=True)

    op.create_table('channellayoutassignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_json', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transition_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transition_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['layout_id'], ['layout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icscache',
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_ics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('widget_id', 'source_url')
    )
    op.create_table('layoutrevision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('zones_json', sa.JSON(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['layout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layoutzone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x_pct', sa.Float(), nullable=False),
    sa.Column('y_pct', sa.Float(), nullable=False),
    sa.Column('w_pct', sa.Float(), nullable=False),
    sa.Column('h_pct', sa.Float(), nullable=False),
    sa.Column('grid_cols', sa.Integer(), nullable=False),
    sa.Column('grid_rows', sa.Integer(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('rotation_seconds', sa.Integer(), nullable=False),
    sa.Column('transition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transition_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transition_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['layout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediafile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['mediafolder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mediafile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mediafile_filename'), ['filename'], unique=True)

    op.create_table('screen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('performance_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_connection_count', sa.Integer(), nullable=False),
    sa.Column('show_offline_banner', sa.Boolean(), nullable=False),
    sa.Column('alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_slug'), ['slug'], unique=True)

    op.create_table('widgetrevision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('name_at_save', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('saved_via', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('editor_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('editor_user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transition_direction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transition_duration_ms', sa.Integer(), nullable=True),
    sa.Column('grid_cols', sa.Integer(), nullable=False),
    sa.Column('grid_rows', sa.Integer(), nullable=False),
    sa.Column('layout_json', sa.JSON(), nullable=True),
    sa.Column('schedule_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['layoutzone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zonewidgetplacement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.Column('inline_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('opacity', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['layoutzone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('view_id', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['view_id'], ['view.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewschedule')
    op.drop_table('zonewidgetplacement')
    op.drop_table('view')
    op.drop_table('widgetrevision')
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_slug'))

    op.drop_table('screen')
    with op.batch_alter_table('mediafile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mediafile_filename'))

    op.drop_table('mediafile')
    op.drop_table('layoutzone')
    op.drop_table('layoutrevision')
    op.drop_table('icscache')
    op.drop_table('channellayoutassignment')
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_edit_token'))

    op.drop_table('widget')
    op.drop_table('mediafolder')
    op.drop_table('layout')
    op.drop_table('channel')
    # ### end Alembic commands ###
