"""Lägg till schemafält på View

Revision ID: 412f6a8d58d1
Revises: 878ff53f7107
Create Date: 2026-04-23 19:21:09.141366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412f6a8d58d1'
down_revision: Union[str, None] = '878ff53f7107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
