"""add duration_seconds to screenlayoutassignment

Revision ID: 5422786eaa8e
Revises: 241c956828fd
Create Date: 2026-04-23 19:58:23.202683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5422786eaa8e'
down_revision: Union[str, None] = '241c956828fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenlayoutassignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenlayoutassignment', schema=None) as batch_op:
        batch_op.drop_column('duration_seconds')

    # ### end Alembic commands ###
