"""lägg till expected_connections på screen

Revision ID: 5527c82cb16e
Revises: 4b0c798d4523
Create Date: 2026-04-24 13:18:29.424665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5527c82cb16e'
down_revision: Union[str, None] = '4b0c798d4523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_connections', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('expected_connections')
    # ### end Alembic commands ###
