"""add view transition override fields

Revision ID: 6df2b025a3fe
Revises: a85b3bdb5420
Create Date: 2026-04-23 21:25:58.158361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df2b025a3fe'
down_revision: Union[str, None] = 'a85b3bdb5420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transition_direction', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transition_duration_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.drop_column('transition_duration_ms')
        batch_op.drop_column('transition_direction')
        batch_op.drop_column('transition')

    # ### end Alembic commands ###
