"""initial

Revision ID: 818bfdce8784
Revises: 
Create Date: 2026-04-21 23:27:50.975165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '818bfdce8784'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rotation_seconds', sa.Integer(), nullable=False),
    sa.Column('performance_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_connection_count', sa.Integer(), nullable=False),
    sa.Column('alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screen_slug'), ['slug'], unique=True)

    op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('edit_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_edit_token'), ['edit_token'], unique=True)

    op.create_table('icscache',
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('raw_ics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('widget_id')
    )
    op.create_table('view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('layout_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetrevision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('name_at_save', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('saved_via', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('editor_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('editor_user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viewschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('view_id', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['view_id'], ['view.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewschedule')
    op.drop_table('widgetrevision')
    op.drop_table('view')
    op.drop_table('icscache')
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_edit_token'))

    op.drop_table('widget')
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screen_slug'))

    op.drop_table('screen')
    # ### end Alembic commands ###
