"""Lägg till schemafält på View

Revision ID: 878ff53f7107
Revises: 1ca11bebfd6b
Create Date: 2026-04-23 19:18:45.618685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '878ff53f7107'
down_revision: Union[str, None] = '1ca11bebfd6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_weekdays', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('schedule_time_start', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('schedule_time_end', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.drop_column('schedule_time_end')
        batch_op.drop_column('schedule_time_start')
        batch_op.drop_column('schedule_weekdays')

    # ### end Alembic commands ###
