"""mediafolder

Revision ID: 98c9b645c091
Revises: 0ef968fa9623
Create Date: 2026-04-23 12:56:00.332127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c9b645c091'
down_revision: Union[str, None] = '0ef968fa9623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediafolder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['mediafolder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mediafile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mediafile_folder_id', 'mediafolder', ['folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediafile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mediafile_folder_id', type_='foreignkey')
        batch_op.drop_column('folder_id')

    op.drop_table('mediafolder')
    # ### end Alembic commands ###
