"""add show_offline_banner transition_direction transition_duration_ms

Revision ID: a85b3bdb5420
Revises: 5422786eaa8e
Create Date: 2026-04-23 21:19:23.397976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85b3bdb5420'
down_revision: Union[str, None] = '5422786eaa8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layoutzone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition_duration_ms', sa.Integer(), nullable=False, server_default='700'))

    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_offline_banner', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('screenlayoutassignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition_direction', sa.String(), nullable=False, server_default='left'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenlayoutassignment', schema=None) as batch_op:
        batch_op.drop_column('transition_direction')

    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('show_offline_banner')

    with op.batch_alter_table('layoutzone', schema=None) as batch_op:
        batch_op.drop_column('transition_duration_ms')

    # ### end Alembic commands ###
