"""view_zone_id

Revision ID: b11165514e37
Revises: 858d348ba2f2
Create Date: 2026-04-23 14:14:52.602483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11165514e37'
down_revision: Union[str, None] = '858d348ba2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_view_zone_id', 'layoutzone', ['zone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.drop_constraint('fk_view_zone_id', type_='foreignkey')
        batch_op.drop_column('zone_id')

    # ### end Alembic commands ###
