"""screen-transition-direction

Revision ID: d98bf7135565
Revises: 230d563f1adf
Create Date: 2026-04-23 12:05:39.283563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98bf7135565'
down_revision: Union[str, None] = '230d563f1adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition_direction', sa.String(), nullable=False, server_default='left'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('transition_direction')

    # ### end Alembic commands ###
