"""aspect-ratio-grid-cols-rows

Revision ID: edf19cd3708f
Revises: 0a4ea825ea71
Create Date: 2026-04-22 21:04:43.042267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf19cd3708f'
down_revision: Union[str, None] = '0a4ea825ea71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aspect_ratio', sa.String(), nullable=False, server_default='16:9'))

    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grid_cols', sa.Integer(), nullable=False, server_default='12'))
        batch_op.add_column(sa.Column('grid_rows', sa.Integer(), nullable=False, server_default='9'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.drop_column('grid_rows')
        batch_op.drop_column('grid_cols')

    with op.batch_alter_table('screen', schema=None) as batch_op:
        batch_op.drop_column('aspect_ratio')

    # ### end Alembic commands ###
