"""add enabled to view and screenlayoutassignment

Revision ID: f5f235e32daf
Revises: 6df2b025a3fe
Create Date: 2026-04-23 21:39:31.055787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f235e32daf'
down_revision: Union[str, None] = '6df2b025a3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenlayoutassignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False, server_default='1'))

    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    with op.batch_alter_table('screenlayoutassignment', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
